name: run shell command

on: push
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps: 
     -  name: echo hello world 
        run: echo "hello worl"
     -  name: list file before
        run: |
         pwd
         ls         
     -  name: checkout action
        uses: actions/checkout@v1
     -  name: list files after
        run: |
          pwd
          ls        
     -  name: multi command
        run: |
          node -v
          npm -v
          
     -  name: run phython command
        run: |
          import platform 
          print (platform.processor())
        shell: python
